name: Publish Web Dev
on:
  push:
    branches:
      [ "main" ]
permissions: 
  contents: write
jobs:
  deploy:
    name: FYPVueJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nodejs and yarn with cache
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
            personal_token: ${{ secrets.commit_secret }}
            publish_dir: dist/
            cname: http://sobanatinah-fyp.firaz-api.site
            allow_empty_commit: true